apiVersion: v1
kind: Service
metadata:
  name: mini-file-server
  labels:
    app: mini-file-server
spec:
  type: ClusterIP
  selector:
    app: mini-file-server
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
